name = input("กรอกชื่อ :\n")
nickname = input("กรอกชื่อเล่น :\n")
age = input("กรอกอายุ :\n")
id = input("กรอกรหัสประจำตัวนักเรียน :\n")
no = input("กรอกชั้นปี :\n")
height = int(input("กรอกส่วนสูง :\n"))
weight = int(input("กรอกน้ำหนัก :\n"))
print('ประวัติโดยย่อ')
print(f"ชื่อ : {name} อายุ : {age} ")
print(f"รหัสประจำตัวนักเรียน :{id} ระดับชั้น : {no} ")
print(nickname)
print(f"ส่วนสูง : {str (height)} น้ำหนัก : {str(weight)}")